media:
  - name: media
    label: Media
    input: public/media
    output: /media
    path: /media

content:
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: bio
        label: Bio
        type: string
        required: false
      - name: avatar
        label: Avatar Image
        type: image
        required: false
      - name: email
        label: Email
        type: string
        required: false
      - name: twitter
        label: Twitter URL
        type: string
        required: false
      - name: linkedin
        label: LinkedIn URL
        type: string
        required: false
      - name: website
        label: Website URL
        type: string
        required: false

  - name: site_config
    label: Site Configuration
    type: file
    format: json
    path: src/config/siteConfig.json
    fields:
      - name: name
        label: Site Name
        type: string
        required: true
      - name: url
        label: Site URL
        type: string
        required: true
      - name: title
        label: Default SEO Title
        type: string
        required: true
      - name: description
        label: Default SEO Description
        type: string
        required: true
      - name: author
        label: Author Name
        type: string
        required: true
      - name: ogImage
        label: Open Graph Image
        type: object
        fields:
          - name: src
            label: Image
            type: image
            required: true
          - name: alt
            label: Image Alt Text
            type: string
            required: true
      - name: social
        label: Social Media Links
        type: object
        fields:
          - name: facebook
            label: Facebook URL
            type: string
            required: false
          - name: linkedin
            label: LinkedIn URL
            type: string
            required: false

  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publication Date
        type: date
        required: true
      - name: description
        label: Description
        type: string
        required: false
      - name: featured_image
        label: Featured Image
        type: image
        required: false
      - name: authors
        label: Authors (comma-separated IDs)
        type: string
        required: false
      - name: tags
        label: Tags (comma-separated)
        type: string
        required: false
      - name: body
        label: Body
        type: rich-text
        required: true
