content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publication Date
        type: date
        required: true
      - name: description
        label: Description
        type: string
        required: false
      - name: featured_image
        label: Featured Image
        type: image
        required: false
      - name: tags
        label: Tags
        type: list
        required: false
        items:
          type: string
      - name: body
        label: Body
        type: rich-text
        required: true
