media:
  - name: media
    label: Media
    input: src/media
    output: /media
    path: /media

content:
  - name: resources
    label: Resources
    type: file
    options:
      path: downloads
      extensions: [pdf]

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Publication Date
        type: date
      - name: description
        label: Description
        type: string
      - name: featured_image
        label: Featured Image
        type: image
      - name: tags
        label: Tags
        type: list
        items:
          type: string
      - name: body
        label: Body
        type: rich-text
